// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbslsywszzbtmprpnuge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJic2xzeXdzenpidG1wcnBudWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTExOTcsImV4cCI6MjA2MTIyNzE5N30.C0wU1niXiVEuLO18YgJCDdbEg3hq4roHtkR_V21g8NQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);